%   f_GetIcons.m [As a part of HFO Detection Project]
%   Written by:
%   Miguel G. Navarrete Mejia
%   Electrical Engineering MS candidate
%   UNIVERSIDAD DE LOS ANDES
%   Colombia, 2012
%   mnavarretem@gmail.com

function st_Icons = f_GetIcons

[m_icon,m_map]      = imread('./Icons/open.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; %#ok<*FNDSB>
st_Icons.open       = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/save.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.save       = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/Import.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.import     = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/print.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.print      = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/save_Int.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.saveInt      = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/clear.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.clear      = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/zoomOutH.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.zoomoutH   = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/zoomInH.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.zoominH    = ind2rgb(m_icon,m_map);


[m_icon,m_map]      = imread('./Icons/zoomOutV.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.zoomoutV   = ind2rgb(m_icon,m_map);

[m_icon,m_map]      = imread('./Icons/zoomInV.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.zoominV    = ind2rgb(m_icon,m_map);


[m_icon,m_map]      = imread('./Icons/hand.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.hand       = ind2rgb(m_icon,m_map);


[m_icon,m_map]      = imread('./Icons/tools_profile.gif');
m_map(find(m_map(:,1)+m_map(:,2)+m_map(:,3)==3)) = NaN; 
st_Icons.tools       = ind2rgb(m_icon,m_map);


st_Icons.datatip    = imread('./Icons/data_cursor.png');
st_Icons.cursors    = imread('./Icons/cursor_icon.bmp');
st_Icons.grid       = imread('./Icons/grid_icon.bmp');
st_Icons.HFODetect  = imread('./Icons/HFO_icon.bmp');
st_Icons.HFOAnalys  = imread('./Icons/HFO_Ana.bmp');

st_Icons.CursorGrab    = ...
          [ NaN	NaN	NaN	NaN	NaN NaN	1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	1	NaN 1	2   1	NaN	1   NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	1	1	NaN 1	2   1	NaN	1   1	NaN	NaN	NaN	NaN;...
            NaN	NaN	1	1	1	NaN 1	2   1	NaN	1   1	1	NaN	NaN	NaN;...
            NaN	1	1	1	1	1   1	2   1	1	1   1	1	1	NaN	NaN;...
            1	1	1	1	1	1   1	2   1	1	1   1	1	1	1  	NaN;...
            NaN	1	1	1	1	1   1	2   1	1	1   1	1	1	NaN	NaN;...
            NaN	NaN	1	1	1	NaN 1	2   1	NaN	1   1	1	NaN	NaN	NaN;...
            NaN	NaN	NaN	1	1	NaN 1	2   1	NaN	1   1	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	1	NaN 1	2   1	NaN	1   NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 1	2   1	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN NaN	NaN NaN	NaN	NaN	NaN NaN	NaN	NaN	NaN];
        
st_Icons.CursorMove    = ...
          [ NaN	NaN	NaN	NaN	NaN 0	0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	NaN   0   0	NaN NaN	NaN	NaN	NaN	NaN];
        
st_Icons.ButtomUp    = ...
          [ NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN NaN	0   0	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	NaN 0	0   0	0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	0   NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN];
        
st_Icons.SmallButtUp    = ...
          [ NaN NaN	0   0	NaN	NaN;...
            NaN 0	0   0	0	NaN;...
            0   0	0   0	0	0  ];
        
st_Icons.ButtomRigh = ...
          [ NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN NaN 0   0	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0	0	0   NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0   NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	0   NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0   0	0   0	0	0   NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0	0	0   0	0	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0   0	0   0	NaN	NaN	NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0	0	0   NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN 0	0	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN	0	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN];
        
st_Icons.ButtomStop = ...
          [ NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0   0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0	0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0   0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	0   0   0	0   0	0	0   0	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN;...
            NaN	NaN	NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN NaN	NaN	NaN	NaN	NaN];        
        
st_Icons.ButtomDown = flipud(st_Icons.ButtomUp);        
st_Icons.ButtomUp   = ...
            cat(3,st_Icons.ButtomUp,st_Icons.ButtomUp,st_Icons.ButtomUp);  
st_Icons.ButtomDown = ...
        cat(3,st_Icons.ButtomDown,st_Icons.ButtomDown,st_Icons.ButtomDown);

st_Icons.SmallButtDown  = flipud(st_Icons.SmallButtUp);        
st_Icons.SmallButtUp    = ...
            cat(3,st_Icons.SmallButtUp,st_Icons.SmallButtUp,...
                st_Icons.SmallButtUp);  
st_Icons.SmallButtDown  = ...
            cat(3,st_Icons.SmallButtDown,st_Icons.SmallButtDown,...
                st_Icons.SmallButtDown);
    
st_Icons.ButtomLeft = fliplr(st_Icons.ButtomRigh);
st_Icons.ButtomRigh   = ...
            cat(3,st_Icons.ButtomRigh,st_Icons.ButtomRigh,st_Icons.ButtomRigh);  
st_Icons.ButtomLeft = ...
        cat(3,st_Icons.ButtomLeft,st_Icons.ButtomLeft,st_Icons.ButtomLeft); 
st_Icons.ButtomStop = ...
        cat(3,st_Icons.ButtomStop,st_Icons.ButtomStop,st_Icons.ButtomStop);
st_Icons.CursorMove = ...
        cat(3,st_Icons.CursorMove,st_Icons.CursorMove,st_Icons.CursorMove);
clc 
end